name: continuous-integration

on: 
  - push:
    branches:
    - master
  - pull_request:
    branches:
    - master 
    
jobs:
  test:
    name: Test on ${{matrix.os}} with dotnet ${{matrix.dotnet}}
  
    runs-on: [ubuntu-latest, windows-latest, macOS-latest]
    strategy:
      matrix:
        dotnet: ['2.2.103', '3.0.100']
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Solution
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      run: |
        dotnet build
        dotnet test
